// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelEntry = `-- name: CancelEntry :exec
UPDATE entries
SET status = 'cancelled'
WHERE id = ?
`

func (q *Queries) CancelEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelEntry, id)
	return err
}

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (
task_name,
hourly_rate,
start_time,
note,
status
) VALUES (
 ?, ?, ?, ?, 'active'
 )
RETURNING id, task_name, hourly_rate, start_time, end_time, flat_fee, status, breaks_json, note
`

type CreateEntryParams struct {
	TaskName   string    `json:"task_name"`
	HourlyRate int64     `json:"hourly_rate"`
	StartTime  time.Time `json:"start_time"`
	Note       string    `json:"note"`
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntry,
		arg.TaskName,
		arg.HourlyRate,
		arg.StartTime,
		arg.Note,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.HourlyRate,
		&i.StartTime,
		&i.EndTime,
		&i.FlatFee,
		&i.Status,
		&i.BreaksJson,
		&i.Note,
	)
	return i, err
}

const createFlatEntry = `-- name: CreateFlatEntry :one
INSERT INTO entries (
    task_name,
    start_time,
    end_time,
    note,
    status,
    flat_fee
) VALUES (
    ?1,
    ?2,
    ?2,
    ?3,
    'completed',
    ?4
)
RETURNING id, task_name, hourly_rate, start_time, end_time, flat_fee, status, breaks_json, note
`

type CreateFlatEntryParams struct {
	TaskName   string    `json:"task_name"`
	LoggedTime time.Time `json:"logged_time"`
	Note       string    `json:"note"`
	FlatFee    int64     `json:"flat_fee"`
}

func (q *Queries) CreateFlatEntry(ctx context.Context, arg CreateFlatEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createFlatEntry,
		arg.TaskName,
		arg.LoggedTime,
		arg.Note,
		arg.FlatFee,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.HourlyRate,
		&i.StartTime,
		&i.EndTime,
		&i.FlatFee,
		&i.Status,
		&i.BreaksJson,
		&i.Note,
	)
	return i, err
}

const endEntry = `-- name: EndEntry :one
UPDATE entries
SET
    end_time = ?,
    status = 'completed'
WHERE id = ?
RETURNING id, task_name, hourly_rate, start_time, end_time, flat_fee, status, breaks_json, note
`

type EndEntryParams struct {
	EndTime sql.NullTime `json:"end_time"`
	ID      int64        `json:"id"`
}

func (q *Queries) EndEntry(ctx context.Context, arg EndEntryParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, endEntry, arg.EndTime, arg.ID)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.HourlyRate,
		&i.StartTime,
		&i.EndTime,
		&i.FlatFee,
		&i.Status,
		&i.BreaksJson,
		&i.Note,
	)
	return i, err
}

const getActiveEntry = `-- name: GetActiveEntry :one
SELECT id, task_name, hourly_rate, start_time, end_time, flat_fee, status, breaks_json, note FROM entries
WHERE status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveEntry(ctx context.Context) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getActiveEntry)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.HourlyRate,
		&i.StartTime,
		&i.EndTime,
		&i.FlatFee,
		&i.Status,
		&i.BreaksJson,
		&i.Note,
	)
	return i, err
}

const listRecentEntries = `-- name: ListRecentEntries :many
SELECT id, task_name, hourly_rate, start_time, end_time, flat_fee, status, breaks_json, note FROM entries
ORDER BY start_time DESC
LIMIT ?
`

func (q *Queries) ListRecentEntries(ctx context.Context, limit int64) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.HourlyRate,
			&i.StartTime,
			&i.EndTime,
			&i.FlatFee,
			&i.Status,
			&i.BreaksJson,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryBreaks = `-- name: UpdateEntryBreaks :exec
UPDATE entries
SET breaks_json = ?
WHERE id = ?
`

type UpdateEntryBreaksParams struct {
	BreaksJson string `json:"breaks_json"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateEntryBreaks(ctx context.Context, arg UpdateEntryBreaksParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryBreaks, arg.BreaksJson, arg.ID)
	return err
}

const updateEntryStatus = `-- name: UpdateEntryStatus :exec
UPDATE entries
SET status = ?
WHERE id = ?
`

type UpdateEntryStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateEntryStatus(ctx context.Context, arg UpdateEntryStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEntryStatus, arg.Status, arg.ID)
	return err
}
