// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Entry struct {
	ID         int64          `json:"id"`
	TaskName   string         `json:"task_name"`
	HourlyRate float64        `json:"hourly_rate"`
	StartTime  time.Time      `json:"start_time"`
	EndTime    sql.NullTime   `json:"end_time"`
	Status     string         `json:"status"`
	BreaksJson sql.NullString `json:"breaks_json"`
	Note       sql.NullString `json:"note"`
}

type EntryTag struct {
	EntryID int64 `json:"entry_id"`
	TagID   int64 `json:"tag_id"`
}

type Tag struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
