// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CancelEntry(ctx context.Context, db DBTX, id int64) error
	CreateEntry(ctx context.Context, db DBTX, arg CreateEntryParams) (Entry, error)
	CreateTag(ctx context.Context, db DBTX, name string) (Tag, error)
	EndEntry(ctx context.Context, db DBTX, arg EndEntryParams) (Entry, error)
	GetActiveEntry(ctx context.Context, db DBTX) (Entry, error)
	GetTagsForEntry(ctx context.Context, db DBTX, entryID int64) ([]Tag, error)
	LinkTagToEntry(ctx context.Context, db DBTX, arg LinkTagToEntryParams) error
	ListAllTags(ctx context.Context, db DBTX) ([]Tag, error)
	ListRecentEntries(ctx context.Context, db DBTX, limit int64) ([]Entry, error)
	UnlinkTagFromEntry(ctx context.Context, db DBTX, arg UnlinkTagFromEntryParams) error
	UpdateEntryBreaks(ctx context.Context, db DBTX, arg UpdateEntryBreaksParams) error
}

var _ Querier = (*Queries)(nil)
