// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name)
VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name
`

func (q *Queries) CreateTag(ctx context.Context, db DBTX, name string) (Tag, error) {
	row := db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTagsForEntry = `-- name: GetTagsForEntry :many
SELECT t.id, t.name FROM tags t
JOIN entry_tags et ON t.id = et.tag_id
WHERE et.entry_id = ?
`

func (q *Queries) GetTagsForEntry(ctx context.Context, db DBTX, entryID int64) ([]Tag, error) {
	rows, err := db.QueryContext(ctx, getTagsForEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTagToEntry = `-- name: LinkTagToEntry :exec
INSERT INTO entry_tags (entry_id, tag_id)
VALUES (?, ?)
`

type LinkTagToEntryParams struct {
	EntryID int64 `json:"entry_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) LinkTagToEntry(ctx context.Context, db DBTX, arg LinkTagToEntryParams) error {
	_, err := db.ExecContext(ctx, linkTagToEntry, arg.EntryID, arg.TagID)
	return err
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name FROM tags ORDER BY name ASC
`

func (q *Queries) ListAllTags(ctx context.Context, db DBTX) ([]Tag, error) {
	rows, err := db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkTagFromEntry = `-- name: UnlinkTagFromEntry :exec
DELETE FROM entry_tags
WHERE entry_id = ? AND tag_id = ?
`

type UnlinkTagFromEntryParams struct {
	EntryID int64 `json:"entry_id"`
	TagID   int64 `json:"tag_id"`
}

func (q *Queries) UnlinkTagFromEntry(ctx context.Context, db DBTX, arg UnlinkTagFromEntryParams) error {
	_, err := db.ExecContext(ctx, unlinkTagFromEntry, arg.EntryID, arg.TagID)
	return err
}
